# Generated by Django 4.2.5 on 2023-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_language_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
