# Generated by Django 4.2.5 on 2023-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_languages_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages_used',
        ),
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.ManyToManyField(blank=True, to='project.programminglanguage'),
        ),
    ]
